Show identifications in viewer 177576899
luomus/laji pull request #116
Opened 2021-05-10 14:13 UTC by MLumme

2021-05-11 13:24 UTC, aorin requested changes
Dev branch should be merged to this as it seems to have some conflicts. Otherwise looks good :thumbsup:. I added some small comments.

2021-05-11 13:24 UTC, aorin commented on projects/laji/src/app/shared-modules/document-viewer/identifications/identification/identification.component.html
> +    <div class="inset">
Laji ui project has some helper classes such as ml-5 (gives 18px margin left) that could be handy here

2021-05-18 06:47 UTC, MLumme commented
@aorin Finally implemented those changes after some docker problems, didn't see anything break, but might want to check also to be sure.

2021-05-18 09:23 UTC, aorin approved these changes
:+1:

2021-05-25 13:01 UTC, merged