More gis fields to frontend 178155718
luomus/laji pull request #130
Opened 2021-05-25 11:05 UTC by MLumme

2021-05-25 12:43 UTC, vixriihi requested changes

2021-05-25 12:43 UTC, vixriihi commented on projects/laji/src/app/shared-modules/observation-result/selected-field-group/selected-field-group.component.html
> +        ></laji-selected-field-item>
Theses two are almost the same could they be joined?

2021-05-25 12:43 UTC, vixriihi commented on projects/laji/src/app/shared-modules/observation-result/selected-field-group/selected-field-group.component.ts
> +      this.getGisFields(field).forEach(column => {
`this.getGisFields` can return `undefined` and that would break

2021-05-26 11:23 UTC, MLumme commented
@vixriihi I simplified the components as requested.

2021-05-26 11:49 UTC, vixriihi approved these changes

2021-05-26 12:32 UTC, merged