Add themes 178408971
luomus/laji pull request #145
Opened 2021-06-04 10:40 UTC by mikkohei13

Adds R-package and bumblebee census to themes page https://178408971.dev.laji.fi/theme

2021-06-04 10:43 UTC, olzraiti requested changes

2021-06-04 10:43 UTC, olzraiti commented on projects/laji/src/app/+theme/theme.component.html
> +    <a [routerLink]="['/project/' + Global.oldThemeRouting['kimalaiset']] | localize" tabindex="-1" class="navbox">
Could you remove the `tabindex` attribute? They will be removed from all other theme items in https://github.com/luomus/laji/pull/114

2021-06-04 10:44 UTC, olzraiti requested changes

2021-06-04 10:44 UTC, olzraiti commented on projects/laji/src/app/+theme/theme.component.html
> +    <a [routerLink]="['/about/3123c1'] | localize" tabindex="-1" class="navbox">
Remove `tabindex` here also

2021-06-04 11:05 UTC, olzraiti approved these changes
:+1:

2021-06-14 05:19 UTC, wkmor1 requested changes
I think the r-package theme should just link straight to https://luomus.github.io/finbif/

2021-06-14 12:22 UTC, wkmor1 approved these changes

2021-06-21 09:11 UTC, merged