Strict function types 180206625
luomus/laji pull request #220
Opened 2021-11-19 15:06 UTC by Blodir

Enables the `strictFunctionTypes` tsc rule.

There's a couple of `any`'s related to third party libraries that I didn't know how to type...

2021-11-22 13:14 UTC, aorin requested changes
Looks good! There is one place that I think could be improved. (Also `projects/laji/src/app/shared-modules/select/select-subcategories/select-subcategories.component.ts` is hard to understand but it's not really related to this pull request)

2021-11-25 08:55 UTC, Blodir commented on projects/laji/src/app/+taxonomy/taxon/taxon.component.ts
>    private initTaxon(taxonId: string): Observable<any> {
True, fixed :)

2021-11-25 09:18 UTC, aorin approved these changes
:+1:

2021-11-26 09:59 UTC, merged

2021-12-10 15:16 UTC, olzraiti commented on projects/laji/src/app/shared-modules/select/select-subcategories/select-subcategories.component.ts
> +      ).length;
BTW this broke the component, see task https://www.pivotaltracker.com/story/show/180599328

```typeof item === 'string' || item.id !== undefined```

is not the same as:
```item.id !== undefined```

I fixed this with:
```typeof item !== 'string' && item.id !== undefined```

2021-12-10 15:39 UTC, olzraiti commented on projects/laji/src/app/shared-modules/select/select-subcategories/select-subcategories.component.ts
> +      ).length;
Hmm, it should be the same though. Maybe some other changes here affecting this. I pushed the above as a hotfix to prod anyways - let's have a better look next week.