More strict typing [#180206625]
luomus/laji pull request #221
Opened 2021-11-19 15:18 UTC by olzraiti

https://www.pivotaltracker.com/story/show/180206625
https://211119.dev.laji.fi

2021-11-26 10:32 UTC, Blodir requested changes

2021-11-26 10:32 UTC, Blodir commented on projects/laji/src/app/shared/service/id.service.ts
> +  static getUri(value: any) {
same as above

2021-11-26 10:32 UTC, Blodir commented on projects/laji/src/app/shared/service/laji-api.interceptor.ts
> +        const data: any[] = [];
`const data: Observable<IFileLoad>[] = [];`
(`IFileLoad` also needs to be exported)

2021-11-26 10:32 UTC, Blodir commented on projects/laji/src/app/shared/service/laji-api.service.ts
> +  private removeUndefinedFromObject<T extends object>(obj: T): T {
Doesn't this line contradict the next one? If T extends object, then there should be no need to check whether obj is an object or not?

2021-11-26 10:35 UTC, olzraiti commented on projects/laji/src/app/shared/service/id.service.ts
> +  static getId(value: any) {
Yeah I tried to refactor this first, but it wasn't very easy and I'd rather not break stuff. The generic is a good idea, I'll apply that

2021-11-26 13:49 UTC, olzraiti commented
Thanks for the review! I addressed the issues.

2021-12-01 10:15 UTC, Blodir approved these changes

2021-12-03 08:36 UTC, merged