Map tilelayers param [#180434670]
luomus/laji pull request #225
Opened 2021-11-25 15:57 UTC by olzraiti

Demo https://180434670.dev.laji.fi/map?layers=afeGrid
Task https://www.pivotaltracker.com/story/show/180434670

* Adds the possibility to preselect any layers via `layers` query param in the URI
* Don't render observation map if there are extra params

2021-12-01 12:01 UTC, Blodir requested changes

2021-12-01 13:58 UTC, olzraiti commented on projects/laji/src/app/+map/front/front.component.ts
>  @Component({
Agree!

2021-12-01 14:03 UTC, olzraiti commented on projects/laji/src/app/+map/front/front.component.ts
> +    const _layers = (_tileLayerNames
`layers` is already reserved in line 65:
```
const {layers, overlayNames, world} = this.route.snapshot.queryParams;
```

`_` prefix is also often used to point out that it's a derivative variable, like in this case `_layers` is derived from `layers`.

2021-12-01 14:09 UTC, olzraiti commented on projects/laji/src/app/+map/front/front.component.ts
> +    const _tileLayerNames = `${(layers ?? '')},${(overlayNames ?? '')}`;
I removed the extra brackets & unnecessary `_tileLayerNames` declaration, and the need for `?? ''`.

2021-12-03 08:56 UTC, Blodir approved these changes

2021-12-03 09:00 UTC, merged