Informal taxon group multi select exclude 180597662
luomus/laji pull request #249
Opened 2022-02-02 12:20 UTC by MLumme

Added tree selection for informal taxon group, changes to autocomplete, filter typing due to new filters, renamed some components, and split a common component out of original collections filter to be used by both it and informal group selector.
Feature branch here https://180597662.dev.laji.fi/

2022-02-02 14:09 UTC, aorin requested changes
When I tested the new feature, I got an error message. Steps to reproduce:
1. Go to https://180597662.dev.laji.fi/observation/list
2. Click “All” button under Informal Groups and then click en empty space
3. Click the button with three dots and then “Select groups” button
4. Error message appears

I glanced though the code and didn't find any major problems. I noticed some small style issues that I marked down, mostly about missing types

2022-02-02 14:41 UTC, MLumme commented on projects/laji/src/app/shared-modules/extended-group-select/extended-group-select.module.ts
> +    LajiUiModule,
SharedModule is required, as the group-select that is used to render the old informal group selector resides there, but common and lajiui-modules are indeed unnecessary.

2022-02-03 09:22 UTC, MLumme commented
These should be fixed now.

2022-02-03 09:44 UTC, aorin approved these changes
Looks good

2022-02-03 10:11 UTC, merged