Audio viewer Safari problem
luomus/laji pull request #287
Opened 2022-05-05 11:43 UTC by aorin

Problem: Audio viewer didn't work at all with older Safari versions

Solution: Problem was caused by old Safari not supporting loading/resampling audio into a sample rate we are using. I noticed that it wasn't necessary to resample the audio in order to draw spectrogram (as long as `nperseg` and `noverlap` parameters take into account the sample rate). Now the audio viewer should work for all browsers (that support Web Audio API).

This pull request is bigger than it should be because I wasn't sure at first how to fix this. I also did some refactoring.

Testable here: https://180916086.dev.laji.fi/theme/kerttu/letters (should look the same than dev except if you are using an old Safari)

2022-05-11 13:30 UTC, olzraiti requested changes
Looks good, left some minor nits.

2022-05-11 13:30 UTC, olzraiti commented on projects/laji/src/app/shared-modules/audio-viewer/audio-viewer/audio-viewer.component.ts
> +    targetWindowOverlapPercentage: 0.375,
These are already in variables file, could they be imported from there?

2022-05-11 14:41 UTC, olzraiti commented on projects/laji/src/app/shared-modules/audio-viewer/audio-viewer/audio-spectrogram/audio-spectrogram.component.ts
> +    ) : 0;
Now you made it like this:

```
a
  ? b : c
  ? d
  : e
```

which is inconsistent. I think having each `?` and `:` on a separate line, and indenting systematically makes it visually easy to understand, like this:

```
  this._height = this.height
    ? this.height
    : this.config
      ? (AudioViewerUtils.getSpectrogramSegmentLength(this.config.targetWindowLengthInSeconds, this.config.sampleRate) / 2)
      : 0;
```

(I didn't notice that width calculation above this has the same problem, maybe we should fix that also to make in consistent)

2022-05-11 14:48 UTC, aorin commented on projects/laji/src/app/shared-modules/audio-viewer/audio-viewer/audio-spectrogram/audio-spectrogram.component.ts
> +    ) : 0;
Ok, let's change it to that. I'm pretty sure that the format in`this._width` has been copied somewhere else, trying to mimic our default format (but we probably doesn't have any default format in this yet)

2022-05-12 10:21 UTC, olzraiti commented
Thanks!

2022-05-12 10:21 UTC, olzraiti approved these changes

2022-05-13 07:58 UTC, merged