Add technical news to all pages #185049817
luomus/laji pull request #432
Opened 2023-08-16 12:52 UTC by MLumme

Task here https://www.pivotaltracker.com/story/show/185049817, probably not on all pages, but then news should now show up on all taxon pages and cms-pages.

2023-08-17 10:16 UTC, aorin requested changes

2023-08-17 10:16 UTC, aorin commented on projects/laji/src/app/+information/information.module.ts
> +import { TechnicalNewsModule } from '../shared-modules/technical-news/technical-news.module';
Not a big issue but it looks a little weird that there is no space between the lines `import ...` and `@NgModule ...`

2023-08-17 10:16 UTC, aorin commented on projects/laji/src/app/+information/information.component.html
> +TEST
This should be removed

2023-08-22 07:23 UTC, MLumme commented on projects/laji/src/app/+information/information.component.html
> +TEST
Both done.

2023-08-22 09:55 UTC, aorin approved these changes
:+1:

2023-08-23 07:58 UTC, merged