Selecting year range as time #184710661
luomus/laji pull request #436
Opened 2023-08-17 12:06 UTC by MLumme

Task here https://www.pivotaltracker.com/story/show/184710661, also added the handler for keypress' to catch enter-keys to set the value.

2023-08-17 12:18 UTC, Blodir requested changes

2023-08-17 12:18 UTC, Blodir commented on projects/laji/src/app/shared/datepicker/datepicker.component.ts
> +    if (e.keyCode === 13) {
Use keycodes from angular cdk https://github.com/angular/components/blob/main/src/cdk/keycodes/keycodes.ts
```
import { ENTER } from '@angular/cdk/keycodes';
```

2023-08-22 07:18 UTC, MLumme commented on projects/laji/src/app/shared/datepicker/datepicker.component.ts
> +    if (e.keyCode === 13) {
Done.

2023-08-22 16:12 UTC, Blodir approved these changes

2023-08-23 07:57 UTC, merged