Dataset metadata publishing #2
luomus/laji pull request #454
Opened 2023-11-08 11:18 UTC by MLumme

Grouping of tasks https://www.pivotaltracker.com/story/show/185927876, https://www.pivotaltracker.com/story/show/185927742, https://www.pivotaltracker.com/story/show/185927868 and https://www.pivotaltracker.com/story/show/185927934. 

Testable at https://185927876.dev.laji.fi/theme/dataset-metadata/.

2023-11-09 15:01 UTC, aorin requested changes

2023-11-10 10:23 UTC, MLumme commented on projects/laji/src/app/shared-modules/dataset-metadata/dataset-metadata-browser/dataset-metadata-browser.component.scss
> +.selector-empty-height {
Not used, removed.

2023-11-10 10:25 UTC, MLumme commented on projects/laji/src/app/shared-modules/dataset-metadata/dataset-metadata.component.scss
> +  min-height: calc(100vh - 50px - 384px);
Originally I added that as it seemed that the sidebar wanished if no collection was selected and it was minimized, but seems it was some odd interaction with the other styles, as it doesn't happen with these changes.

2023-11-10 10:26 UTC, MLumme commented on projects/laji/src/app/shared-modules/dataset-metadata/dataset-metadata.component.ts
> +      this.updateCollection(params.collectionId);
Done.

2023-11-10 10:26 UTC, MLumme commented on projects/laji/src/app/shared-modules/dataset-metadata/dataset-metadata.component.ts
>    _collectionId: string;
And done.

2023-11-10 10:26 UTC, MLumme commented on projects/laji/src/app/shared-modules/dataset-metadata/dataset-metadata.component.ts
>    changeUrl(collectionId) {
Should be done.

2023-11-10 11:04 UTC, aorin commented on projects/laji/src/app/shared-modules/dataset-metadata/dataset-metadata.component.scss
> +  min-height: calc(100vh - 50px - 384px);
I was able to broke the sidebar by resizing the screen with firefox so I added a commit to fix it. Can you check that it's fine?

2023-11-10 11:10 UTC, MLumme commented on projects/laji/src/app/shared-modules/dataset-metadata/dataset-metadata.component.scss
> +  min-height: calc(100vh - 50px - 384px);
Will do, and I'm not surprised something broke, it's a pretty finiky thing with so many nested levels from all the components.

2023-11-10 11:49 UTC, aorin approved these changes
Thanks, looks good!

2023-11-13 09:04 UTC, merged