Display taxon not found message
luomus/laji pull request #502
Opened 2024-03-04 08:56 UTC by Blodir

https://www.pivotaltracker.com/story/show/186579262
https://186579262.dev.laji.fi/taxon/MX.50934850937845

2024-03-06 10:39 UTC, MLumme requested changes

2024-03-06 10:39 UTC, MLumme commented on projects/laji/src/app/+taxonomy/taxon/taxon.component.ts
> +  errorWas404 = false;
Isn't this unnecessary variable?

2024-03-06 15:19 UTC, Blodir commented on projects/laji/src/app/+taxonomy/taxon/taxon.component.ts
> +  errorWas404 = false;
yep

2024-03-07 07:58 UTC, MLumme approved these changes
LGTM

2024-03-07 14:13 UTC, merged