Species descriptions
luomus/laji pull request #541
Opened 2024-09-10 06:48 UTC by aorin

https://www.pivotaltracker.com/story/show/188126690
https://188126690.dev.laji.fi/taxon/MX.39862

Changes how the descriptions are shown in the taxon card. The overview tab shows either the general description or the structure description, and the biology tab shows all the descriptions. Contains quite much refactoring to the related components.

2024-09-30 09:14 UTC, Blodir requested changes

2024-09-30 09:14 UTC, Blodir commented on projects/laji/src/app/+taxonomy/taxon/info-card/taxon-biology/taxon-biology.component.html
> +            <div style="float:left; width: 100%">
this styling with floats and also bs3 columns and such is not preferable, but it's okay since I guess this was not changed in this PR

2024-09-30 09:14 UTC, Blodir commented on projects/laji/src/app/+taxonomy/taxon/info-card/shared/service/taxon-description-lang.service.ts
> +export class TaxonDescriptionLangService {
I think it would be fine to just have these functions in `info-card.component.ts` since they don't seem to be used elsewhere

2024-09-30 13:22 UTC, aorin commented on projects/laji/src/app/+taxonomy/taxon/info-card/shared/service/taxon-description-lang.service.ts
> +export class TaxonDescriptionLangService {
We have quite many this kind of services (like the shared `utils.service` and `id.service`) but yeah I agree that the normal functions work better for this. I guess the functions could be in the `info-card.component` but it's quite a big component already, I think it improves readability having them elsewhere.

2024-10-01 20:25 UTC, Blodir approved these changes

2024-10-02 07:23 UTC, merged