Accuracy filter slider at incorrect position #184453892
luomus/laji pull request #555
Opened 2024-09-26 09:36 UTC by MLumme

https://www.pivotaltracker.com/story/show/184453892
https://184453892.dev.laji.fi/observation/list?coordinateAccuracyMax=100

Added initalization from query parameter to the accuracy slider, before it was always at default value regardless of query parameters value, removed box shadow from the accuracy and coordinate overlap slider due to chrome bug, added margin-to to coordinate-sections hr-separators to more clearly separate different subsections.

2024-09-26 12:56 UTC, Blodir requested changes

2024-09-26 12:56 UTC, Blodir commented on projects/laji/src/app/+observation/form/observation-form.component.scss
> +#coordSeparator {
ids are exclusive (you shouldn't have two elements with the same id on the same page). Use a class instead

2024-09-26 12:56 UTC, Blodir commented on projects/laji/src/app/+observation/form/observation-form.component.html
> +                (input)="onAccuracySliderChange()"
I'd probably change the name here to reflect that the event has changed to `input` i.e. `onAccuracySliderInput()`

2024-09-27 07:54 UTC, MLumme commented
@Blodir Implemented your changes, and  moved the codeblock that sets the accuracy value from parameters to a different function, the current form stopped working, and seemed to have worked only by accident.

2024-09-30 07:28 UTC, Blodir approved these changes

2024-10-02 07:20 UTC, merged