Fix various bugs with the common panel/accordion component
luomus/laji pull request #576
Opened 2024-10-08 07:47 UTC by Blodir

Related (copied from slack):

Ramble about angular animations: There have been various issues with the panels including this one, things overlapping on the observation page, taxon info card maps breaking, etc. These are all caused by angular animations (especially in combination with ssr/hydration).

Issues:
1. the SSR generated html includes invalid syntax like style=""height=*;" (this comes from angular animations wildcard).
2. After hydration completes animation state doesn't update even if the predicate changes during hydration
3. Since the animation targets the height property, sometimes the height updates correctly, but no resize event is emitted to child nodes (which breaks the map)
4. Other stuff I guess...

We do have animations on some other components that seem to not have issues (eg. sidebar), but I can't seem to figure out why it breaks for laji-panel . Luckily the animations are pretty unnecessary for the component so I will just remove them. These issues have been horrible to debug.

https://www.pivotaltracker.com/story/show/188283099
Fixes bullet points 1 and 3.

2024-10-08 07:52 UTC, olzraiti requested changes

2024-10-08 07:52 UTC, olzraiti commented on projects/laji/src/app/shared/panel/panel.component.html
> +<div class="panel-collapse" [ngStyle]="{display: open ? 'block' : 'none' }" role="tabpanel" aria-labelledby="">
`aria-labelledby=""` is unnecessary

2024-10-08 07:52 UTC, olzraiti commented on projects/laji/src/app/shared/panel/panel.component.ts
> +import {Component, EventEmitter, Input, Output, TemplateRef } from '@angular/core';
missing space after `{`

2024-10-08 07:59 UTC, olzraiti approved these changes

2024-10-08 07:59 UTC, merged

2024-10-10 09:28 UTC, Blodir commented
Fixes #571