Improve template typing 176920498
luomus/laji pull request #61
Opened 2021-02-22 12:30 UTC by vixriihi

This enables strict typings in templates

2021-02-24 16:01 UTC, olzraiti requested changes
Whew, thanks for the effort! I commented on a few things that caught my eyes.

2021-02-25 06:39 UTC, vixriihi commented on projects/laji/src/app/+taxonomy/species/species-form/species-form.component.html
> +              (selectedChange)="onInvasiveChange($event[0])"></laji-select>
Good catch :) Was trying to find the spot where that option had effect. Will look into this to see if this can be fixed quickly in this pr

2021-02-25 07:17 UTC, vixriihi commented on projects/laji/src/app/+project-form/results/wbc-result/wbc-species-charts/wbc-species-linecharts/wbc-species-linecharts.component.ts
> +  LineWithLine = 'LineWithLine' as chartJs.ChartType;
Ah da good I was wondering why I couldn't use typecasting here :) (should have checked the ChartType)

2021-02-25 07:33 UTC, vixriihi commented on projects/laji/src/app/+taxonomy/species/species-form/species-form.component.html
> +              (selectedChange)="onInvasiveChange($event[0])"></laji-select>
I think the behavior in beta for example is correct... maybe :) At least now it's mimicking that closely

2021-02-25 10:48 UTC, merged