Result service butterfly bumblebee census 170074940
luomus/laji pull request #72
Opened 2021-03-08 12:44 UTC by Hvar83

2021-03-10 09:25 UTC, olzraiti commented
Is this ready for reviewing or still under development? I took a quick look and noticed for example that this breaks the result service for NAFI (https://170074940.dev.laji.fi/project/MHL.6/stats has a "routes" sub nav link which doesn't do anything and there reads "content" after the title).

2021-03-10 09:43 UTC, Hvar83 commented
@olzraiti As i still don't receive anything about resultServiceType from API, i set in project-form component form resultService to nafiBumblebee. Just remove that line and nafi is working

2021-03-10 09:48 UTC, olzraiti commented
The forms (MHL.59 & MHL.89) didn't have any result service set. I added the result service for them just now.

2021-03-10 10:02 UTC, Hvar83 commented
@olzraiti ok

2021-03-10 12:16 UTC, olzraiti commented
Let's follow the new development process here, so that this enters into reviewing only after the task has been approved in Pivotal. Please notify here when it's been approved.

2021-05-25 06:48 UTC, MLumme commented
@olzraiti this has now been approved for review bu PO.

2021-05-25 12:00 UTC, olzraiti requested changes
The comments have mostly very minor stuff (unused vars etc), but on top of that I also get warnings when I start the dev server:

```
Error: projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-result-filters/nafi-bumblebee-result-filters.component.html:21:48 - error TS2339: Property 'value' does not exist on type 'EventTarget'.

21           (change)="onDateChange($event.target.value !== '0' ? $event.target.value : undefined)"
                                                  ~~~~~

  projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-result-filters/nafi-bumblebee-result-filters.component.ts:9:16
    9   templateUrl: './nafi-bumblebee-result-filters.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component NafiBumblebeeResultFiltersComponent.


Error: projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-result-filters/nafi-bumblebee-result-filters.component.html:21:78 - error TS2339: Property 'value' does not exist on type 'EventTarget'.

21           (change)="onDateChange($event.target.value !== '0' ? $event.target.value : undefined)"
                                                                                ~~~~~

  projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-result-filters/nafi-bumblebee-result-filters.component.ts:9:16
    9   templateUrl: './nafi-bumblebee-result-filters.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component NafiBumblebeeResultFiltersComponent.


Error: projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-result-filters/nafi-bumblebee-result-filters.component.html:7:48 - error TS2339: Property 'value' does not exist on type 'EventTarget'.

7           (change)="onYearChange($event.target.value !== '0' ? $event.target.value : undefined)"
                                                 ~~~~~

  projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-result-filters/nafi-bumblebee-result-filters.component.ts:9:16
    9   templateUrl: './nafi-bumblebee-result-filters.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component NafiBumblebeeResultFiltersComponent.


Error: projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-result-filters/nafi-bumblebee-result-filters.component.html:7:78 - error TS2339: Property 'value' does not exist on type 'EventTarget'.

7           (change)="onYearChange($event.target.value !== '0' ? $event.target.value : undefined)"
                                                                               ~~~~~

  projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-result-filters/nafi-bumblebee-result-filters.component.ts:9:16
    9   templateUrl: './nafi-bumblebee-result-filters.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component NafiBumblebeeResultFiltersComponent.


Error: projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-route/nafi-bumblebee-route.component.html:29:6 - error TS2322: Type 'string' is not assignable to type 'SEASON'.

29     [season]="date"
        ~~~~~~

  projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-route/nafi-bumblebee-route.component.ts:12:16
    12   templateUrl: './nafi-bumblebee-route.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component NafiBumblebeeRouteComponent.


Error: projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-route/nafi-bumblebee-route.component.html:31:6 - error TS2322: Type 'number' is not assignable to type 'string'.

31     [year]="activeYear"
        ~~~~

  projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-route/nafi-bumblebee-route.component.ts:12:16
    12   templateUrl: './nafi-bumblebee-route.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component NafiBumblebeeRouteComponent.


Error: projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-routes/nafi-bumblebee-routes-list/nafi-bumblebee-routes-list.component.html:16:6 - error TS2322: Type 'string' is not assignable to type 'ColumnMode | "standard" | "flex" | "force"'.

16     [columnMode]="columnMode"
        ~~~~~~~~~~

  projects/laji/src/app/+project-form/results/nafi-bumblebee-result/nafi-bumblebee-routes/nafi-bumblebee-routes-list/nafi-bumblebee-routes-list.component.ts:10:16
    10   templateUrl: './nafi-bumblebee-routes-list.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component NafiBumblebeeRoutesListComponent.
```

Also, I think all the variables & files should be renamed (nafi bumblebee -> syke insect projects). Should be possible with `sed` & `rename` in unix. I can try the renaming if you could check those errors above first.

2021-05-26 08:46 UTC, olzraiti requested changes
Found one more unnecessary var. Also the conflicts need to be fixed.

2021-05-26 08:46 UTC, olzraiti commented on projects/laji/src/app/+project-form/results/syke-insect-result/syke-insect-result.component.ts
> +    this.lang = this.translate.currentLang;
rm unused var (didn't notice this last round).

2021-05-26 10:01 UTC, olzraiti approved these changes
:+1:

2021-05-26 10:02 UTC, merged